---
- block:
  - name: Download alertmanager package
    get_url:  
      url: "{{ alertmanager_pkg_url }}"
      dest: "/tmp/alertmanager.tgz"
  
  - name: Install alermanager binaries
    unarchive:
      src: "/tmp/alertmanager.tgz"
      dest: "/tmp"
      remote_src: yes


- name: Generate alertmanager config
  template:
    src: alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml
    mode: 0644
    owner: root


