---
- name: Download alertmanager package
  unarchive:
    remote_src: "{{ alertmanager_pkg_url }}"
    dest: "/tmp/alertmanager"
    creates: "/tmp/alertmanager"

- name: Generate alertmanager config
  template:
    src: alertmanager.yml.j2
    dest: /etc/prometheus/alertmanager.yml
    mode: 0644
    owner: root


